### ISSUE TITLE
SCIPhI fails silently if mpileup does not use reference file

### ISSUE THREAD

**Issue by winni2k** [cbg-ethz/SCIPhI#17]
I tried running `sciphi` on an mpileup file that I generated with the command

```
samtools mpileup -A -B -d 100000 -q 40 -Q 30 -b input_samples.list > out.mpileup
```

The resulting output file had data in the format

```
1       4117397 N       16      GgGggGggggGgGggg        @?@??_??@?@@@@@@        13      GGGgggggGggGg   A`A???@?`@@@?
```

Note the third column containing the letter `N`.

`sciphi` ran for several days before delivering an empty VCF. I then tried again using the `-f` option to provide a reference FASTA. The resulting mpileup had the form 

```
1       4117397 G       16      .,.,,.,,,,.,.,,,        @?@??_??@?@@@@@@        13      ...,,,,,.,,.,   A`A???@?`@@@?
```

and I was able to obtain a VCF that contained sensible variant and genotype calls from `sciphi`.  

Is `sciphi` meant to work on an mpileup file that has `N` as the reference allele?

**Comment by singerj** [comment]
Yes, SCIPhI assumes that the reference allele is know and provided during the pileup generation. In fact, it simply did not cross my mind that you could have situations where it is not known. This could be a nice extension, however, it has no high priority at the moment.

Thank you for pointing this out!

**Comment by winni2k** [comment]
What is supposed to happen to sites that have `N` as the reference allele? Are they supposed to be filtered out before tree/genotype estimation? If so, it does not look like that is what is currently happening. It looks like SCIPhI tries to perform inference on those sites anyway?

If the sites with reference allele `N` were to be filtered out before inference, then my situation would become obvious very quickly. I'd be happy to implement such a filter.

**Comment by singerj** [comment]
Hi,

You are right. The assumption that every base of the genome for some organism is known is very strong and does often not hold. Therefore, SCIPhI ignores positions where the reference is not known now. Thanks for poiting it out.

**Comment by winni2k** [comment]
It looks like caf1bf84796f9a908be7de17e66164de62d29dd9 implements this feature?

**Comment by singerj** [comment]
Yes, and it should work now. Sorry for the inconvenience.

**Comment by winni2k** [comment]
Thanks for the fix!
