### ISSUE TITLE
SCIPhI does not compile

### ISSUE THREAD

**Issue by winni2k** [cbg-ethz/SCIPhI#18]
When I run the following commands on the current master branch (caf1bf84796f9a908be7de17e66164de62d29dd9):

```
git clone https://github.com/cbg-ethz/SCIPhI.git --recursive
cd SCIPhI
mkdir mybuild
cd mybuild
cmake ..
cmake --build . --config Release
```

then I get lots of compilation errors. I am attaching the STDERR from the build to this issue.
[build.txt](https://github.com/cbg-ethz/SCIPhI/files/3540994/build.txt)

Commit fe944792abe20f13f0849a38cecdb8fb43b4e353 compiles without problems for me.

**Comment by winni2k** [comment]
Commit 518e825 also compiles on my machine.

**Comment by singerj** [comment]
Sorry for the inconvenience. The issue is now resolved.

**Comment by winni2k** [comment]
Excellent.

Perhaps it might be worth setting up a continuous integration for compilation and testing?
