### ISSUE TITLE
VERSION_STRING is not defined

### ISSUE THREAD

**Issue by dpryan79** [cbg-ethz/SCIPhI#20]
src/output.h:91 uses a `VERSION_STRING` constant, which is not defined. That prevents compilation, such as in bioconda: https://circleci.com/gh/bioconda/bioconda-recipes/93822?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Xref: https://github.com/bioconda/bioconda-recipes/pull/20181

**Comment by winni2k** [comment]
Thanks for the heads up! @singerj I have made a PR with the fix. 

Once the PR is merged, a new release will be necessary and an update of the bioconda recipe. Not sure if you want to bump the patch version for that or if you want to retag v0.1.6 (possibly evil).

**Comment by singerj** [comment]
Hi there, thanks for looking into the issue and even fixing it! I have no clue how it made it into the repo like this and I am really sorry for any inconvenience! Thanks again!
