### ISSUE TITLE
Input requirements

### ISSUE THREAD

**Issue by biobenkj** [cbg-ethz/SCIPhI#6]
I'm very excited to use SCIPhI but have a few questions regarding the input.

The documentation states it requires a pileup format which makes sense but there is also a link to the GATK best practices that appears that you need BQSR bams prior to running samtools pileup as input into SCIPhI. Is this correct?

Thanks!

**Comment by singerj** [comment]
Hi,

The alignment and BAM file processing steps are up to the user and can be adapted to the special needs as seems most appropriate. The link to the GATK best practices is only meant as a hint of how this can be done in practice, but there is no dependence on any special tool prior to samtools mpileup.

I hope that helps! 

Best,
Jochen

**Comment by biobenkj** [comment]
Thanks for the response! It took a little work to get the dependencies to play nicely but finally got it to compile (not the tests though). Re-reading the pre-print clarifies my original comment :) Align > dedup > indel realign > mpileup.

**Comment by winni2k** [comment]
@biobenkj regarding compiling the tests: I managed to get the tests to compile by using cmake and turning the `BUILD_DIAGNOSTICS` switch on.  So instead of running

```
cmake ..
```

from the build directory, I ran

```
cmake -DBUILD_DIAGNOSTICS=ON ..
```

HTH
